name = "Beyond"
author = "Ramon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9713ff34833c0437ece3f98a28d4b19e522c65910b0af0feba38d1f57f43026"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
