name = "Beyond"
author = "Ramon"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1433d00432aec591152e37604238fc7b644ad8aa77c3899888e2bb4bbbd6cac8"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
