name = "Beyond"
author = "Ramon"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8562538c4c80cfbf59f21d7c68a79485a74f195dd50849398bf65493f26d035"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
