name = "Beyond"
author = "Ramon"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3096b05da059e35eba777cbde82341c73d63ccd30eac5aa24962037165860ad6"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
