name = "Beyond"
author = "Ramon"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aceca3dc6f587f95d6241ce1f6e3d5929fd85ac8b5ef06c990119885b24b8796"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
